### ISSUE TITLE
ERROR: SET_DATAx never go to zero

### ISSUE THREAD

**Issue by sebastian-freitag-pylot** [markusj/upd72020x-load#12]
I was curious and tried it on my card. Something went wrong. Could it be, I already have a newer firmware? Some info below:
```
~$ lspci -nn
00:00.0 Host bridge [0600]: Intel Corporation Device [8086:3e30] (rev 0d)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 0d)
00:01.1 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x8) [8086:1905] (rev 0d)
00:02.0 VGA compatible controller [0300]: Intel Corporation Device [8086:3e98] (rev 02)
00:08.0 System peripheral [0880]: Intel Corporation Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th Gen Core Processor Gaussian Mixture Model [8086:1911]
00:12.0 Signal processing controller [1180]: Intel Corporation Cannon Lake PCH Thermal Controller [8086:a379] (rev 10)
00:14.0 USB controller [0c03]: Intel Corporation Cannon Lake PCH USB 3.1 xHCI Host Controller [8086:a36d] (rev 10)
00:14.2 RAM memory [0500]: Intel Corporation Cannon Lake PCH Shared SRAM [8086:a36f] (rev 10)
00:16.0 Communication controller [0780]: Intel Corporation Cannon Lake PCH HECI Controller [8086:a360] (rev 10)
00:16.3 Serial controller [0700]: Intel Corporation Device [8086:a363] (rev 10)
00:17.0 SATA controller [0106]: Intel Corporation Cannon Lake PCH SATA AHCI Controller [8086:a352] (rev 10)
00:1b.0 PCI bridge [0604]: Intel Corporation Device [8086:a340] (rev f0)
00:1d.0 PCI bridge [0604]: Intel Corporation Device [8086:a333] (rev f0)
00:1f.0 ISA bridge [0601]: Intel Corporation Device [8086:a309] (rev 10)
00:1f.3 Audio device [0403]: Intel Corporation Cannon Lake PCH cAVS [8086:a348] (rev 10)
00:1f.4 SMBus [0c05]: Intel Corporation Cannon Lake PCH SMBus Controller [8086:a323] (rev 10)
00:1f.5 Serial bus controller [0c80]: Intel Corporation Cannon Lake PCH SPI Controller [8086:a324] (rev 10)
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (7) I219-LM [8086:15bb] (rev 10)
01:00.0 Ethernet controller [0200]: Intel Corporation Ethernet Controller 10G X550T [8086:1563] (rev 01)
01:00.1 Ethernet controller [0200]: Intel Corporation Ethernet Controller 10G X550T [8086:1563] (rev 01)
02:00.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X2G608GP PCIe2 6-Port/8-Lane Packet Switch [12d8:2608]
03:01.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X2G608GP PCIe2 6-Port/8-Lane Packet Switch [12d8:2608]
03:02.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X2G608GP PCIe2 6-Port/8-Lane Packet Switch [12d8:2608]
03:03.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X2G608GP PCIe2 6-Port/8-Lane Packet Switch [12d8:2608]
03:04.0 PCI bridge [0604]: Pericom Semiconductor PI7C9X2G608GP PCIe2 6-Port/8-Lane Packet Switch [12d8:2608]
04:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720202 USB 3.0 Host Controller [1912:0015] (rev 02)
05:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720202 USB 3.0 Host Controller [1912:0015] (rev 02)
06:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720202 USB 3.0 Host Controller [1912:0015] (rev 02)
07:00.0 USB controller [0c03]: Renesas Technology Corp. uPD720202 USB 3.0 Host Controller [1912:0015] (rev 02)
08:00.0 Network controller [0280]: PEAK-System Technik GmbH Device [001c:001a] (rev 01)
09:00.0 Ethernet controller [0200]: Intel Corporation I210 Gigabit Network Connection [8086:1533] (rev 03)

~$ sudo ./upd72020x-load -u -b 0x05 -d 0x00 -f 0x0 -i UPDATE.mem 
Doing the upload
bus = 5 
dev = 0 
fct = 0 
fname = UPDATE.mem 
Found an UPD720202 chipset
got firmware version: 202609
EEPROM installed
got rom_info: c22010
got rom_config: 700
setting rom_config: 700
STATUS: enabling firmware upload
STATUS: performing firmware upload
ERROR: SET_DATAx never go to zero
 ======> FAILED

~$ sha256sum UPDATE.mem 
177560c224c73d040836b17082348036430ecf59e8a32d7736ce2b80b2634f97  UPDATE.mem
```

**Comment by markusj** [comment]
Might be the same problem as described in #7. I updated the script to execute the steps proposed by user cranphin. Could you please try either the script or do those steps manually?

**Comment by sebastian-freitag-pylot** [comment]
```
echo -n 0000:04:00.0 > /sys/bus/pci/drivers/xhci_hcd/unbind
echo -n 0000:05:00.0 > /sys/bus/pci/drivers/xhci_hcd/unbind
echo -n 0000:06:00.0 > /sys/bus/pci/drivers/xhci_hcd/unbind
echo -n 0000:07:00.0 > /sys/bus/pci/drivers/xhci_hcd/unbind
./upd72020x-load -u -b 0x04 -d 0x00 -f 0x0 -i UPDATE.mem 
./upd72020x-load -u -b 0x05 -d 0x00 -f 0x0 -i UPDATE.mem 
./upd72020x-load -u -b 0x06 -d 0x00 -f 0x0 -i UPDATE.mem 
./upd72020x-load -u -b 0x07 -d 0x00 -f 0x0 -i UPDATE.mem 
echo -n 0000:04:00.0 > /sys/bus/pci/drivers/xhci_hcd/bind
echo -n 0000:05:00.0 > /sys/bus/pci/drivers/xhci_hcd/bind
echo -n 0000:06:00.0 > /sys/bus/pci/drivers/xhci_hcd/bind
echo -n 0000:07:00.0 > /sys/bus/pci/drivers/xhci_hcd/bind
```

This worked flawlessly on all 4 of my controllers.

**Comment by markusj** [comment]
Thanks. I will add some comment about this to the README and then close this issue. I am not sure yet if I want to add this to the binary itself, most likely not.

**Comment by pclinuxer** [comment]
Hello:
First of all, thanks for this utility.
I've been needing to get this card to work for the longest time.

I have come across a problem I don't know how to deal with.

My card is properly reported in lspsci:

[root@devuan work]# lspci
04:00.0 USB controller: Renesas Technology Corp. uPD720201 USB 3.0 Host Controller (rev 03)
[root@devuan work]# 
ie: lists vendor as being Renesas - lists chip as being uPD720201

I got my hands on a FW file from this site:
https://raw.githubusercontent.com/chunkeey/renesas-fw/master/USB3-201-202-FW-20120615.zip

The file comes with a release note:
>
****************************************************************************
****** D720201 & D720202 Design Resources Release ******
****************************************************************************
 Release Note                                                   June 15.2012
 
 Renesas Electronics D720201 & uPD720202
 USB3.0 Host Controller Firmware

 Version : 2.0.1.3 :June 15th, 2012
 Copyright (C) 2011-2012 Renesas Electronics Corporation All Rights Reserved
****************************************************************************************************

Note : This firmware is for the following devices.
      - uPD720201 ES 2.0 sample whose revision ID (in the PCI Configuration 
       Register) is 2h.
      - uPD720201 ES 2.1 sample & CS sample & Mass product whose revision
       ID (in the PCI Configuration Register) is 3h.
      - uPD720202 ES 2.0 sample & CS sample & Mass product whose revision
       ID (in the PCI Configuration Register) is 2h.

So it would seem (?) that what lspci is reporting would be the uPD720201 Mass product revision ID is 3h.

But when I run the loader I get this:

``
[root@devuan work]#   ./upd72020x-load -u -b 0x04 -d 0x00 -f -i 0x00 K2013080.mem
Doing the upload
bus = 4 
dev = 0 
fct = 0 
fname = (null) 
ERROR: wrong vendorid/devid. Expected an UPD720201 or UPD720202 chip and this is not one!
       reported vendorid/devid: 1912:0014 
 ======> FAILED
``
Now, it turns out that the vendorid/devid: 1912:0014 reported seems to be the right one:
This is the first hit from the well nown and ubiquitous search engine:
>
Vendor Devices
Type	PCI
Vendor ID	1912
Vendor Name	Renesas Technology Corp.
Device ID	0014
Device Name	uPD720201 USB 3.0 Host Controller

Where's the discrepancy?
The firmware seems to be a correct match for the card but ...

Any help you could give me would be greatly appreciated.

Thanks in advance.
