### ISSUE TITLE
USB powering problem

### ISSUE THREAD

**Issue by zokl** [markusj/upd72020x-load#13]
Hello, thank you very much for your nice work. I used it for my project based on OpenWRT (https://github.com/k13132/openwrt-packages/tree/master/packages/upd72020x-loader). I used China's mPCIE to USB3.0 converter FG-MU302A (https://www.aliexpress.com/item/1791121083.html?spm=a2g0s.9042311.0.0.27424c4dCpAOEU). Your application loads the firmware. Linux is able to show USB3.0 hub but without devices. The problem is powering the devices. I think that the powering is not activated. 

Do you know where could be a problem?

Thank you, Zbynek Kocur

**Comment by markusj** [comment]
I am sorry, but I am not familiar with any other internals of the upd72020x chipset family since I only focused on the firmware upload process. Afterwards the card just worked for me with the kernel drivers without further configuration. Thus, I can not provide you any help with your problem. You might take a look into the data sheet to see if there are any hints about how the bus power is controlled by the chipset, but I would expect this to be a task of the kernel driver (but one could argue the same about the firmware upload ...).

I close this issue since it is not related to upd72020x-load itself.
